[colors.bright]
black = "#767C77"
red = "#FF1A75"
green = "#1AFFA3"
yellow = "#FFFF00"
blue = "#FFAA54"
magenta = "#28C9FF"
cyan = "#09FFF2"
white = "#F9F9F9"

[colors.normal]
black = "#232323"
red = "#FF5454"
green = "#00CC7A"
yellow = "#FFD700"
blue = "#FF7431"
magenta = "#00BFFF"
cyan = "#48D1CC"
white = "#BFBFBF"

[colors.primary]
background = "#121212"
foreground = "#BFBFBF"

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Medium" }
size = 14

[font.offset]
x = 1
y = 1
