[colors.primary]
  background = '#000000'
  foreground = "#BFBFBF"

[colors.cursor]
  text = '#F9F9F9'
  cursor = '#BFBFBF'

[colors.normal]
  black =   '#232323'
  red =     '#FF5454'
  green =   '#00CC7A'
  yellow =  '#FFD700'
  blue =    '#00bFFF'
  magenta = '#FF00FF'
  cyan =    '#48d1cc'
  white =   '#bfbfbf'

[colors.bright]
  black =   '#767c77'
  red =     '#ff1a75'
  green =   '#1affa3'
  yellow =  '#ffff00'
  blue =    '#28c9ff'
  magenta = '#ff33ff'
  cyan =    '#09fff2'
  white =   '#f9f9f9'

[font]
  normal = { family = "Inconsolata Nerd Font Mono", style = "Medium" }
  size = 14

[font.offset]
  x = 1
  y = 1

[window]
  opacity = 1
