# Light high-contrast theme for Alacritty
[colors.primary]
  background = '#FFFFFF'
  foreground = "#000000"

[colors.cursor]
  text = '#FFFFFF'
  cursor = '#000000'

[colors.normal]
black = '#000000'
red = '#D00000'
green = '#007500'
yellow = '#B86600'
blue = '#0000D0'
magenta = '#A000A0'
cyan = '#007B7B'
white = '#505050'

# Bright colors
[colors.bright]
black = '#686868'
red = '#D00000'
green = '#007500'
yellow = '#B86600'
blue = '#0000D0'
magenta = '#A000A0'
cyan = '#007B7B'
white = '#000000'