# This file should be in "$XDG_CONFIG_HOME/tmuxp/dev.yml"

session_name: dev
start_directory: $HOME/dev/

windows:
  - window_name: terms
    layout: tiled
    panes:
      -
  - window_name: terms
    layout: tiled
    panes:
      -
