#!/bin/sh
# opout: "open output": A general handler for opeing a file's intented output.
# I find this useful escpecilly running from vim.

basename="$(echo "$1" | sed 's/\.[^\/.]*$//')"

case "$1" in
	*.tex|*.md|*.rmd|*.ms|*.me|*.mom) setsid "$READER" "$basename".pdf >/dev/null 2>&1 & ;;
	*.html) setsid "$BROWSER" --new-window "basename".html >/dev/null 2>&1 & ;;
esac
